from pathlib import Path

p = Path("app/src/main/java/com/ahbe/mylauncher/MainActivity.kt")
s = p.read_text(encoding="utf-8")

old_activity = '''class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { LauncherRoot() }
    }
}'''
new_activity = '''class MainActivity : ComponentActivity() {
    private var iconRefreshGeneration by mutableIntStateOf(0)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { LauncherRoot(iconRefreshGeneration) }
    }

    override fun onResume() {
        super.onResume()
        // Some apps (Telegram is a common example) switch launcher aliases/icons
        // without changing package name. Refresh launcher metadata and icon state
        // whenever this launcher becomes active again.
        iconRefreshGeneration++
    }
}'''
if old_activity not in s:
    raise SystemExit("MainActivity anchor not found")
s = s.replace(old_activity, new_activity, 1)

if "private fun LauncherRoot() {" not in s:
    raise SystemExit("LauncherRoot anchor not found")
s = s.replace(
    "private fun LauncherRoot() {",
    "private fun LauncherRoot(iconRefreshGeneration: Int) {",
    1,
)

# Dashboard AppTile call generated by the v21 gesture patch.
old = "                                        iconCache = iconCache,\n                                        iconSize = iconSize,"
new = "                                        iconCache = iconCache,\n                                        iconRefreshGeneration = iconRefreshGeneration,\n                                        iconSize = iconSize,"
if old not in s:
    raise SystemExit("AppTile call anchor not found")
s = s.replace(old, new, 1)

# AppTile function signature.
old = "    iconCache: LruCache<String, ImageBitmap>,\n    iconSize: Int,\n    isDragging: Boolean,"
new = "    iconCache: LruCache<String, ImageBitmap>,\n    iconRefreshGeneration: Int,\n    iconSize: Int,\n    isDragging: Boolean,"
if old not in s:
    raise SystemExit("AppTile signature anchor not found")
s = s.replace(old, new, 1)

# The existing v21 cache key already includes rendered pixel size. Add the
# active launcher activity plus resume generation, so runtime icon/alias changes
# cannot reuse a stale bitmap from a previous foreground session.
old = '''    val cacheKey = remember(app.packageName, iconPx) { "${app.packageName}@$iconPx" }
    var icon by remember(cacheKey) { mutableStateOf(iconCache.get(cacheKey)) }'''
new = '''    val cacheKey = remember(app.packageName, app.activityName, iconPx, iconRefreshGeneration) {
        "${app.packageName}|${app.activityName}@$iconPx#$iconRefreshGeneration"
    }
    var icon by remember(cacheKey) { mutableStateOf(iconCache.get(cacheKey)) }'''
if old not in s:
    raise SystemExit("AppTile cache key anchor not found")
s = s.replace(old, new, 1)

# App picker path: refresh miniature icons too.
old = "                iconCache = iconCache,\n                onRefresh = { refreshKey++ },"
new = "                iconCache = iconCache,\n                iconRefreshGeneration = iconRefreshGeneration,\n                onRefresh = { refreshKey++ },"
if old not in s:
    raise SystemExit("AppPicker call anchor not found")
s = s.replace(old, new, 1)

old = "    iconCache: LruCache<String, ImageBitmap>,\n    onRefresh: () -> Unit,"
new = "    iconCache: LruCache<String, ImageBitmap>,\n    iconRefreshGeneration: Int,\n    onRefresh: () -> Unit,"
if old not in s:
    raise SystemExit("AppPicker signature anchor not found")
s = s.replace(old, new, 1)

if "MiniAppIcon(app, iconCache)" not in s:
    raise SystemExit("MiniAppIcon call anchor not found")
s = s.replace(
    "MiniAppIcon(app, iconCache)",
    "MiniAppIcon(app, iconCache, iconRefreshGeneration)",
    1,
)

old = "private fun MiniAppIcon(app: AppEntry, iconCache: LruCache<String, ImageBitmap>) {"
new = "private fun MiniAppIcon(app: AppEntry, iconCache: LruCache<String, ImageBitmap>, iconRefreshGeneration: Int) {"
if old not in s:
    raise SystemExit("MiniAppIcon signature anchor not found")
s = s.replace(old, new, 1)

old = '''    val context = LocalContext.current
    var icon by remember(app.packageName) { mutableStateOf(iconCache.get(app.packageName)) }
    LaunchedEffect(app.packageName) {
        if (icon == null) {
            val loaded = withContext(Dispatchers.IO) { runCatching { loadAppIcon(context.applicationContext, app, 80).asImageBitmap() }.getOrNull() }
            loaded?.let { iconCache.put(app.packageName, it); icon = it }
        }
    }'''
new = '''    val context = LocalContext.current
    val cacheKey = remember(app.packageName, app.activityName, iconRefreshGeneration) {
        "${app.packageName}|${app.activityName}@80#$iconRefreshGeneration"
    }
    var icon by remember(cacheKey) { mutableStateOf(iconCache.get(cacheKey)) }
    LaunchedEffect(cacheKey) {
        if (icon == null) {
            val loaded = withContext(Dispatchers.IO) { runCatching { loadAppIcon(context.applicationContext, app, 80).asImageBitmap() }.getOrNull() }
            loaded?.let { iconCache.put(cacheKey, it); icon = it }
        }
    }'''
if old not in s:
    raise SystemExit("MiniAppIcon cache anchor not found")
s = s.replace(old, new, 1)

# Refresh PackageManager launcher metadata on resume as well. This is essential
# for apps that implement alternate icons by enabling a different activity-alias:
# the package name stays the same, but the active launcher component changes.
marker = "    val dark = isSystemInDarkTheme()\n"
refresh_effect = '''    LaunchedEffect(iconRefreshGeneration) {
        if (iconRefreshGeneration > 0) {
            iconCache.evictAll()
            withContext(Dispatchers.IO) { runCatching { queryLauncherApps(appContext) } }
                .onSuccess { loaded ->
                    if (loaded.isNotEmpty()) {
                        installedApps = loaded
                        prefs.edit().putString(KEY_APP_CACHE, encodeAppCache(loaded)).apply()
                    }
                }
        }
    }

'''
if marker not in s:
    raise SystemExit("theme anchor not found")
s = s.replace(marker, refresh_effect + marker, 1)

p.write_text(s, encoding="utf-8")
print("Applied v28 dynamic icon + launcher alias refresh")
